# Generated by Django 4.1.3 on 2023-03-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deactivate_date',
        ),
    ]
