# Generated by Django 4.1.3 on 2023-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_activate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
    ]
