# Generated by Django 4.1.3 on 2023-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
