# Generated by Django 4.1.3 on 2023-03-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_note_activate_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
    ]
