# Generated by Django 4.1.3 on 2023-03-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_note_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
